name: finar
description: "Jellyfin client"
publish_to: 'none'
version: 5.0.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  # Playback
  media_kit: ^1.2.5
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7

  # State
  flutter_riverpod: ^2.5.1

  # Network
  dio: ^5.4.0
  connectivity_plus: ^7.0.0

  # Images & assets
  cached_network_image: ^3.3.1
  flutter_svg: ^2.3.0
  flutter_animate: ^4.5.0

  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2

  # Utils
  intl: ^0.19.0
  uuid: ^4.3.3
  path: ^1.9.0
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.8

flutter:
  uses-material-design: true

  assets:
    - icon.svg
